name: cucumber java and maven project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Maven Clean  
      run: mvn clean install
   #- name: Set Execute Permissions for Chromedriver
    # run: chmod +x src/test/resources/drivers/chromedriver.exe
    - name: Run Cucumber Tests  
      run: mvn test
